In [1]:
import numpy as np
import pandas as pd

**Creating data frames**

In [4]:
data = {
    'Name': ['john','anna', 'peter', 'linda'],
    'Age': [28,34,29,42],
    'City': ['jaipur', 'Delhi', 'Kota', 'Sikar'],
    'Salary': [65000,32000,76000,52000]
}
df = pd.DataFrame(data)
df

    Name  Age    City  Salary
0   john   28  jaipur   65000
1   anna   34   Delhi   32000
2  peter   29    Kota   76000
3  linda   42   Sikar   52000

In [5]:
data_list = [
    ['jhon', 20, 'jaipur', 65000],
    ['anna', 30, 'Delhi', 34000],
    ['peter', 29, 'Kota', 69000],
    ['Linda', 69, 'sikar', 26000]
]
df1 = pd.DataFrame(data_list)

In [6]:
df1

       0   1       2      3
0   jhon  20  jaipur  65000
1   anna  30   Delhi  34000
2  peter  29    Kota  69000
3  Linda  69   sikar  26000

In [7]:
columns = ['Name', 'Age', 'City', 'Salary']

In [8]:
# df3 = pd.DataFrame(data_list, columns)
df2 = pd.DataFrame(data_list, columns= columns)
df2

    Name  Age    City  Salary
0   jhon   20  jaipur   65000
1   anna   30   Delhi   34000
2  peter   29    Kota   69000
3  Linda   69   sikar   26000

**selection and indexinf**

In [9]:
df1[0]  # --> List me index 0,1,2,...

0     jhon
1     anna
2    peter
3    Linda
Name: 0, dtype: object

In [10]:
df2['Name']  # --> Dictionary me indexing by labels hoti hai

0     jhon
1     anna
2    peter
3    Linda
Name: Name, dtype: object

In [11]:
df2[['Name','City']] # Multiple Column Select at a time

    Name    City
0   jhon  jaipur
1   anna   Delhi
2  peter    Kota
3  Linda   sikar

Create a new column

In [12]:
# add column work
df2["Work"] = ['A', 'B', 'C', 'D']

In [13]:
df2

    Name  Age    City  Salary Work
0   jhon   20  jaipur   65000    A
1   anna   30   Delhi   34000    B
2  peter   29    Kota   69000    C
3  Linda   69   sikar   26000    D

In [14]:
df2['Work']

0    A
1    B
2    C
3    D
Name: Work, dtype: object

Remove a column

In [15]:
df2.drop('Work', axis=1)   # without axis is gives error, pure area ko remove nhi karta hai

    Name  Age    City  Salary
0   jhon   20  jaipur   65000
1   anna   30   Delhi   34000
2  peter   29    Kota   69000
3  Linda   69   sikar   26000

In [16]:
df2

    Name  Age    City  Salary Work
0   jhon   20  jaipur   65000    A
1   anna   30   Delhi   34000    B
2  peter   29    Kota   69000    C
3  Linda   69   sikar   26000    D

In [17]:
df2.drop('Work', axis=1, inplace=True)  # --> it parmanently remove

In [18]:
df2

    Name  Age    City  Salary
0   jhon   20  jaipur   65000
1   anna   30   Delhi   34000
2  peter   29    Kota   69000
3  Linda   69   sikar   26000

In [19]:
row = ['a','b','c','d']
df3 = pd.DataFrame(data_list, columns = columns, index=row)

In [20]:
df3

    Name  Age    City  Salary
a   jhon   20  jaipur   65000
b   anna   30   Delhi   34000
c  peter   29    Kota   69000
d  Linda   69   sikar   26000

In [21]:
df3.drop('a')  # --> pure area ko remove nhi karta hai

    Name  Age   City  Salary
b   anna   30  Delhi   34000
c  peter   29   Kota   69000
d  Linda   69  sikar   26000

In [22]:
df3

    Name  Age    City  Salary
a   jhon   20  jaipur   65000
b   anna   30   Delhi   34000
c  peter   29    Kota   69000
d  Linda   69   sikar   26000

In [23]:
# remove multiple data at a time
df3.drop(['City', 'Salary'], axis = 1, inplace=True)

In [24]:
df3

    Name  Age
a   jhon   20
b   anna   30
c  peter   29
d  Linda   69

In [27]:
# df3 = df2.copy()
df3 = df2
df3

    Name  Age    City  Salary
0   jhon   20  jaipur   65000
1   anna   30   Delhi   34000
2  peter   29    Kota   69000
3  Linda   69   sikar   26000

In [26]:
# select single row
df3.loc[0] # loc() --> Location

Name        jhon
Age           20
City      jaipur
Salary     65000
Name: 0, dtype: object

In [27]:
# Select Multiple rows
df3.loc[[0,2]]

    Name  Age    City  Salary
0   jhon   20  jaipur   65000
2  peter   29    Kota   69000

Selecting Subset of Rows and Columns

In [28]:
df3.loc[[0,1],['Name','Age']]

   Name  Age
0  jhon   20
1  anna   30

In [29]:
df3.loc[[0,1]][['Name','Salary']]

   Name  Salary
0  jhon   65000
1  anna   34000

Conditional Selection

In [16]:
df2

    Name  Age    City  Salary Work
0   jhon   20  jaipur   65000    A
1   anna   30   Delhi   34000    B
2  peter   29    Kota   69000    C
3  Linda   69   sikar   26000    D

In [29]:
df2[df2['Age']>=30 ]

    Name  Age   City  Salary
1   anna   30  Delhi   34000
3  Linda   69  sikar   26000

In [18]:
df2[(df2['Age']>=30) & (df2['Salary']>30000)]

   Name  Age   City  Salary Work
1  anna   30  Delhi   34000    B