In [1]:
import numpy as np
import pandas as pd

Missing Data

In [3]:
# Finding missing data

In [3]:
data = {
    'A': [1, 2, np.nan, 4, 5],             # np.nan ==> NULL Value
    'B': [np.nan, 2, 3, 4, 5],            
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [4]:
df.isna()    # NULL values pe True

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [6]:
df.isna().sum()  # It count total NULL values in a column

A    1
B    1
C    2
D    3
dtype: int64

In [15]:
df.isna().any()     # column me at least ek null value hai to true

A    True
B    True
C    True
D    True
dtype: bool

In [16]:
#  Removing Missing Data
#     based on rows

In [8]:
data = {
    'A': [1, 2, np.nan, 4, 5],             # np.nan ==> NULL Value
    'B': [1, 2, 3, 4, 5],            
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df1 = pd.DataFrame(data)

In [27]:
df1

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [9]:
df1.dropna()  # return karta hai jisme koi bhi NULL values nhi ho

     A  B    C    D
0  1.0  1  1.0  1.0

In [31]:
df1.dropna(thresh=3)   # at least 3 not null values in a row

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [32]:
df1.dropna(thresh=4)

     A  B    C    D
0  1.0  1  1.0  1.0

In [ ]:
# Filling the missing data

In [11]:
df1.fillna(100)

       A  B      C      D
0    1.0  1    1.0    1.0
1    2.0  2    2.0  100.0
2  100.0  3    3.0  100.0
3    4.0  4  100.0  100.0
4    5.0  5  100.0    5.0

In [35]:
df1  # ==> parmanent ke liye inplace=True likhna padega

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [13]:
value  = {'A':0, 'B':100, 'C':200, 'D':400}
df1.fillna(value)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  200.0  400.0
4  5.0  5  200.0    5.0